openapi: 3.0.0
info:
  title: Social App
  description: Our first social app supporting LinkedIn, Instagram and Facebook accounts details
  version: 1.0.0
servers:
- url: http://localhost:5000/api/v1
  description: Localhost version of our social app
- url: https://localhost:5000/api/v1
  description: This is just a dummy url, it doesn't work
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
